# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/jobdialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newJobDialog(object):
    def setupUi(self, newJobDialog):
        newJobDialog.setObjectName("newJobDialog")
        newJobDialog.resize(623, 232)
        self.buttonBox = QtWidgets.QDialogButtonBox(newJobDialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 190, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(newJobDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 40, 621, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.documentName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.documentName.setObjectName("documentName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.documentName)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pageCount = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.pageCount.setMinimum(1)
        self.pageCount.setObjectName("pageCount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pageCount)
        self.label_4 = QtWidgets.QLabel(newJobDialog)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 601, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(newJobDialog)
        self.buttonBox.accepted.connect(newJobDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(newJobDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(newJobDialog)

    def retranslateUi(self, newJobDialog):
        _translate = QtCore.QCoreApplication.translate
        newJobDialog.setWindowTitle(_translate("newJobDialog", "Enter New Job Details"))
        self.label.setText(_translate("newJobDialog", "Document Name:"))
        self.label_2.setText(_translate("newJobDialog", "Pages:"))
        self.label_4.setText(_translate("newJobDialog", "New Job Details"))
